Dev
dkrasnykh/praktikum-diploma pull request #2
Opened 2024-02-26 12:30 UTC by dkrasnykh

2024-03-01 07:27 UTC, bambruysk requested changes
Нужно продумать как обрабатывать 429 статус

В остальном очень хорошо

2024-03-01 07:27 UTC, bambruysk commented on cmd/gophermart/internal/api/middleware.go
> +	userCtx             = "userID"
лучше не называть Ctx  такие  константы. Кажется что это контекст, но на деле это не так
Согласно кодстайлу от uber, которым пользуются плюс минус большинство команд у нас, неэкспортируемые переменные лучше называть начиная с _

2024-03-01 07:27 UTC, bambruysk commented on cmd/gophermart/internal/api/order.go
> +		switch err {
такой код не реагирует на обернутые ошибки 

лучше так 
```

switch
    case errors.Is(err, errs.ErrOrderExist):
	    newErrorResponse(c, http.StatusOK, err.Error())
    case errors.Is(err, errs.ErrUnreachableOrder):
	    newErrorResponse(c, http.StatusConflict, err.Error())

                     //
```

2024-03-01 07:27 UTC, bambruysk commented on cmd/gophermart/internal/api/http.go
> +	service *service.Service
Здесь лучше использовать интерфейс для ограничения использования сервисом

2024-03-01 07:27 UTC, bambruysk commented on cmd/gophermart/internal/config/config.go
> +	var c Config
чтобы не возиться с & постоянно, можно использовать с := new(Config) или с := &Config{}. Просто подсказка,  не к исправлению

2024-03-01 07:27 UTC, bambruysk commented on cmd/gophermart/internal/service/accrual.go
> +func (a *Accrual) sendRequest(number string) {
функция называется sendRequest но на деле она еще и что-то сохраняет в базу - лучше разделить ее на две. Одна будет получать ответы от аккруала, вторая будет сохранять в базу.

2024-03-01 07:27 UTC, bambruysk commented on cmd/gophermart/internal/service/accrual.go
> +	}
429 код не обрабатывается

2024-03-01 07:27 UTC, bambruysk commented on cmd/gophermart/internal/service/accrual.go
> +			go a.sendRequest(number)
а нам действительно нужно выполнять эти запрсоы в отдельных горутинах? Если да, то можем ли мы обеспечить рейтлимит?

2024-03-01 07:27 UTC, bambruysk commented on cmd/gophermart/internal/service/accrual.go
> +		numbers, err := a.storage.GetProcessingOrders(context.Background())
пустой контекст лучше не использовать. Лучше пробросить сюда общий контекст приложения и на его основе собрать контекст с таймаутом

2024-03-01 07:27 UTC, bambruysk commented on cmd/gophermart/internal/service/order.go
> +	err = o.storage.Add(ctx, userID, orderNumber)
не учитываается транзакционность, то есть у нас две операции с базой, связанные друг с другом. Пользователь может удалиться. В целом в рамках данного проекта это момент можно опустить, но следует помнить, что подобная логика требует внимания. Можно реализовать транзакции как задачу со звездочкой)

2024-03-01 07:27 UTC, bambruysk commented on cmd/gophermart/internal/service/withdrawals.go
> +	if int64(balance.Current*100) < int64(req.Sum*100) {
если обе части неравенства поделить или умножить, то результат не изменится
Основная проблема в использовании поля типа float? Может его вообще не использовать?

2024-03-01 07:27 UTC, bambruysk commented on cmd/gophermart/internal/storage/withdrawals_postgres.go
> +	return &models.UserBalance{Current: float32(debit-credit) / 100, Withdrawn: float32(credit) / 100}, nil
вот эта часть относится скорее к бизнес-логике

2024-03-07 07:04 UTC, dkrasnykh commented on cmd/gophermart/internal/service/accrual.go
> +func (a *Accrual) sendRequest(number string) {
Внесла изменения - у меня два варианта реализации - отправила на проверку другой пул реквест - https://github.com/dkrasnykh/praktikum-diploma/pull/3 . В нём внесла изменения по всем комментариям - посмотри, поджалуйста.

2024-03-12 13:31 UTC, bambruysk approved these changes
Принято

2024-03-12 13:31 UTC, bambruysk commented on cmd/gophermart/internal/service/accrual/accrual.go
> +		return &order, nil
https://pkg.go.dev/github.com/go-resty/resty/v2#Request.SetResult - У рести есть встроенная поддержка JSON -  попробуй, несколько упрощает код

2024-03-13 10:03 UTC, merged